### ISSUE TITLE
Raw source for pastes

### ISSUE THREAD

**Issue by Lysxia** [lpaste/lambda-paste#2]
It would be nice to have a link to the raw version of a paste (a current workaround is to add `raw/` by hand, but that's not practical).

It's also annoying that the rendered pastes are not copy-pastable; line numbers get in the way.

**Comment by int-e** [comment]
@chrisdone: Could you please explain why you closed this? Having a link from the paste page to the raw source would be convenient.

As for the second problem, this CSS trick seems to work for Firefox at least:
```css
.nosel { -moz-user-select: none; -webkit-user-select: none; user-select: none }
```
and later
```html
<td class="nosel"><a href="#line1">1</a></td>
```
